# SPDX-License-Identifier: Apache-2.0
# Source: https://github.com/crossplane/crossplane
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md

package:
  name: crossplane
  version: 2.1.1   
  epoch: 0
  description: "Crossplane is an open-source Kubernetes add-on that enables platform engineering"
  target-architecture:
    - x86_64
    - aarch64
  url: "https://crossplane.io/"
  copyright:
    - license: Apache-2.0
      paths:
        - "*"


environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle
      #- busybox
      #- go
      #- git
      #- make

pipeline:
  - name: "Prepare extraction directory"
    runs: |
      mkdir -p crossplane

  - name: "Download Crossplane source"
    uses: fetch
    with:
      uri: https://github.com/crossplane/crossplane/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha512: 2b0bd9d6c907f270c509aad069037fe8b56e6af1bd61f46ea58a2213ffe7d6c287478038d12902f1460ae068b680eaecc77fd31fbca8d0c7b8f1ccb45c57e779 
      directory: crossplane
      delete: true

  - name: "Build Crossplane binary"
    uses: go/build
    with:
      modroot: crossplane
      packages: ./cmd/crossplane
      ldflags: "-s -X github.com/crossplane/crossplane/v2/internal/version.version=v${{package.version}}"
      output: crossplane


  - uses: strip

  - name: "Cleanup"
    runs: |
      rm -rf crossplane

