# SPDX-FileCopyrightText: 2026 EvoCloud, Inc.
# SPDX-License-Identifier: MPL-2.0

# Source: https://github.com/cloudprober/cloudprober
# Reference: https://github.com/cloudprober/cloudprober/blob/main/Makefile
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md


package:
  name: cloudprober
  version: 0.14.1
  epoch: 1
  description: "An active monitoring software to detect failures before your customers do.."
  target-architecture:
    - x86_64 #supported architectures: 386, amd64, arm/v6, arm/v7, arm64, ppc64le, s390x, x86_64, aarch64, and all that builds it for all of them
  copyright:
    - license: Apache-2.0
    - attestation: |
        Created by the EvoCloud Engineering Team. 
        Copyright (C) 2026 EvoCloud, Inc.
      license: MPL-2.0
      paths:
        - "*"
  url: "https://github.com/cloudprober/cloudprober"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle

vars:
  git_commit: "403ab84188cf9e32594cb6ade6899602cb8f5c5e"
  build_date: "2026-01-28T10:39:35Z"

pipeline:
  #https://github.com/chainguard-dev/melange/blob/main/pkg/build/pipelines/git-checkout.yaml
  - name: "DOWNLOADING CLOUDPROBLER SOURCE CODE"
    uses: git-checkout
    with:
      repository: https://github.com/cloudprober/cloudprober
      expected-commit: ${{vars.git_commit}}
      tag: v${{package.version}}

  - name: "PATCHING GO MODULES"
    # secfixes:
    #   0.14.1-r1:
    #     - GHSA-j5w8-q4qc-rx2x
    #     - GHSA-f6x5-jh6r-wrfv
    runs: |
      go get golang.org/x/crypto@v0.45.0
      go mod tidy
      go mod vendor

  - name: "BUILD CLOUDPROBLER BINARY"
    uses: go/build
    with:
      modroot: .
      packages: ./cmd/cloudprober
      ldflags: |
        -s 
        -X main.version=${{package.version}}
        -X main.buildTimestamp=${{vars.build_date}}
        -X main.dirty=clean
      output: cloudprober

  - uses: strip

update:
  enabled: true
  github:
    identifier: cloudprober/cloudprober
    strip-prefix: v
