# SPDX-FileCopyrightText: 2026 EvoCloud, Inc.
# SPDX-License-Identifier: MPL-2.0
#
# Source: https://github.com/fluxcd/image-reflector-controller
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md
# Reference: https://github.com/fluxcd/image-reflector-controller/blob/main/Makefile

package:
  name: image-reflector-controller
  version: 1.0.4
  epoch: 1
  description: "The GitOps Toolkit container registry scanner"
  target-architecture:
    - x86_64 #supported architectures: 386, amd64, arm/v6, arm/v7, arm64, ppc64le, s390x, x86_64, aarch64, and all that builds it for all of them
  copyright:
    - attestation: |
        Created by the EvoCloud Engineering Team. 
        Copyright (C) 2026 EvoCloud, Inc.
      license: MPL-2.0
      paths:
        - "*"
  url: "https://github.com/fluxcd/image-reflector-controller"
  #dependencies:
  #  runtime:
  #    - bubblewrap

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle

vars:
  git_commit: "82454c4d88b1b933d5760593709c3cc64fb0e1fa"

pipeline:
  #https://github.com/chainguard-dev/melange/blob/main/pkg/build/pipelines/git-checkout.yaml
  - name: "DOWNLOADING IMAGE-REFLECTOR-CONTROLLER SOURCE CODE"
    uses: git-checkout
    with:
      repository: https://github.com/fluxcd/image-reflector-controller
      expected-commit: ${{vars.git_commit}}
      tag: v${{package.version}}

  - name: "PATCHING GO MODULES"
    # secfixes:
    #   1.0.4-r1:
    #     - GHSA-j5w8-q4qc-rx2x
    #     - GHSA-f6x5-jh6r-wrfv
    runs: |
      go get golang.org/x/crypto@v0.45.0
      go mod tidy
      go mod vendor

  - name: "BUILDING IMAGE-REFLECTOR-CONTROLLER BINARY"
    uses: go/build
    with:
      modroot: .
      packages: .
      ldflags: -s 
      output: image-reflector-controller

  - uses: strip #Strip debugging symbols

update:
  enabled: true
  github:
    identifier: fluxcd/image-reflector-controller
    strip-prefix: v  
 
