# SPDX-License-Identifier: Apache-2.0
# Source: https://github.com/kubernetes-sigs/external-dns
# Schema: https://github.com/chainguard-dev/melange/blob/main/docs/BUILD-FILE.md
# Reference: https://github.com/clastix/kamaji/blob/master/Makefile
package:
  name: Kamaji
  version: 25.11.5
  epoch: 1
  description: "Kamaji is the Hosted Control Plane Manager for Kubernetes."
  target-architecture:
    - x86_64
    - aarch64
  url: "https://github.com/clastix/kamaji"
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle
      #- busybox
      #- go


vars:
  git_commit: "ac7da5745441907a82684ebe44d11ab0b0bf3e79"
  git_repo: "https://github.com/clastix/kamaji"
  build_time: "2025-11-29T13:04:42Z"



pipeline:
  - name: "Prepare extraction directory"
    runs: |
      mkdir -p kamaji

  - name: "Download kamaji source"
    uses: fetch
    with:
      uri: https://github.com/clastix/kamaji/archive/refs/tags/edge-${{package.version}}.tar.gz
      expected-sha512: 7b67675ae5177d67c52ade905277526049772726a53d48fc74db813330bb839c1aea57abb2c946722e606eeb93c9cc996ad8a6e740ec187edc282ca8e0e729f6 
      directory: kamaji
      delete: true

  - name: "BUILD KAMAJI BINARY"
    uses: go/build
    with:
      modroot: kamaji
      packages: .
      # secfixes:
      #   25.11.5-r1:
      #     - GHSA-f6x5-jh6r-wrfv
      #     - GHSA-j5w8-q4qc-rx2x 
      deps: golang.org/x/crypto@v0.45.0  
      ldflags: |
        -s 
        -X github.com/clastix/kamaji/internal.GitCommit=${{vars.git_commit}} 
        -X github.com/clastix/kamaji/internal.GitTag=${{package.version}} 
        -X github.com/clastix/kamaji/internal.GitDirty=clean
        -X github.com/clastix/kamaji/internal.BuildTime=${{vars.build_time}}
        -X github.com/clastix/kamaji/internal.GitRepo=${{vars.git_repo}}

      output: kamaji


  - uses: strip

  - name: "Cleanup"
    runs: |
      rm -rf kamaji
